<?php
$jsversion = (isset($js_files_version) && $js_files_version) ? $js_files_version : "";
?>

<!-- jQuery -->
<script src="/adm/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI -->
<script src="/adm/plugins/jquery-ui/jquery-ui.min.js"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>

<!-- Bootstrap 5 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Plugins -->
 <script src="/adm/plugins/URI.min.js"></script>
<script src="/adm/plugins/toastr/toastr.min.js"></script>
<script src="/adm/plugins/sweetalert2/sweetalert2.min.js"></script>

<!-- SECTION PLUGINS -->
<?=$App::$footer_scripts;?>

<!-- Core Scripts -->
<script src="/utils.js?v=<?=$jsversion;?>"></script>
<script src="/app.js?v=<?=$jsversion;?>"></script>
<script src="/adm/plugins/require.js"></script>

<script>
    require.config({
        urlArgs: "bust=" + (new Date()).getTime(),
        waitSeconds: 200
    });
</script>

<!-- SECTION SCRIPTS -->
<?=$App::$footer_section_scripts;?>

</body>
</html>