<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?=$GLOBALS['admin_title'] . " - " . $App::getSectionTitle();?></title>

    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/adm/plugins/fontawesome-free/css/all.min.css">
    
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    
    <!-- Plugins CSS -->
    <link rel="stylesheet" href="/adm/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="/adm/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">
    <link rel="stylesheet" href="/adm/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

    <!-- CUSTOM -->
    <?=$App::$header_scrits;?>


     <!-- Custom Styles -->
    <link rel="stylesheet" href="/adm/css/style2.css?v=1.4">
    
</head>
<body>