<?php

//
include PATH_BASE.DS.'js_versioning.phtml';


//
$user_info = $App::GetUserData();
//var_dump($user_info); exit;


//
$App::$header_scrits = <<<EOF
    <!-- DataTables -->
    <link rel="stylesheet" href="/adm/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="/adm/plugins/summernote/summernote-bs4.min.css">
EOF;


//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/jquery-form/jquery.form.min.js"></script>
    <script src="/adm/plugins/jquery-validation/jquery.validate.js"></script>
    
    <!-- DataTables  & Plugins -->
    <script src="/adm/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/adm/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="/adm/plugins/jszip/jszip.min.js"></script>
    <script src="/adm/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="/adm/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script src="/adm/plugins/summernote/summernote-bs4.min.js"></script>
EOF;




///
$App::$footer_section_scripts = <<<EOF
    <script src="/adm/js/sections-handler.js?v=$js_files_version"></script>
    <script src="/app/products/config.js?v=$js_files_version"></script>
EOF;



//
$App::setSectionInfo("Configuracion", "productos_servicios");


?>

<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'header.phtml'; ?>
<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'aside-menu.phtml'; ?>




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">

                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active"><?=$App::getSectionTitle();?></li>
                        </ol>


                    </div><!-- /.col -->
                    <div class="col-sm-6 text-right">

                        <a href="/admin/products/accesorios/index" class="btn btn-flat btn-warning"><i class="fas fa-reply"></i> Back </a>

                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">




                <form method="post" id="form_section" name="form_section" enctype="multipart/form-data">

                    <div class="row">
                        <div class="col-sm-6 col-lg-6 col-md-6 col-12">
                            <h4>Products Config</h4>
                        </div>
                        <div class="col-sm-6 col-lg-6 col-md-6 col-12 text-right">
                            <br />
                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-save"></i> Save
                            </button>
                            <button type="button" class="btn btn-flat btn-default" id="btnReloadConfig"><i class="fas fa-sync"></i> </button>
                        </div>
                    </div>

                    <hr />

                    <div class="row">
                        <div class="col-sm-4 col-lg-4 col-md-4 col-12" style="">
                            <label for="meal_plans_discount">Meal Plans Discount%:</label>
                            <input data-rule-required="true" data-rule-number="true" type="text" class="form-control" name="meal_plans_discount" id="meal_plans_discount" placeholder="%">
                        </div>
                        <div class="col-sm-4 col-lg-4 col-md-4 col-12" style="">
                            <label for="subscriptions_discount">Subscriptions Discount%:</label>
                            <input data-rule-required="true" data-rule-number="true" type="text" class="form-control" name="subscriptions_discount" id="subscriptions_discount" placeholder="%">
                        </div>
                    </div>

                </form>









                    <div class="row">
                        <div class="col-sm-8 col-lg-8 col-md-8 col-12">
                            <h4>Sizes - <span class="product-title"></span></h4>
                        </div>
                        <div class="col-sm-4 col-lg-4 col-md-4 col-12 text-right">
                            <br />
                            <button type="button" class="btn btn-flat btn-default" id="btnReloadTaxes"><i class="fas fa-sync"></i> </button>
                        </div>
                    </div>

                    <br />

                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <table id="grid_taxes" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>Id:</th>
                                            <th>State:</th>
                                            <th>Tax:</th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                    <!-- /.row -->





            </div>
        </section>
    </div><!-- /.container-fluid -->



<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'footer.phtml'; ?>