<?php

//
include PATH_BASE.DS.'js_versioning.phtml';
//
$user_info = $App::GetUserData();
//var_dump($user_info); exit;


//
$App::$header_scrits = <<<EOF
    <link rel="stylesheet" href="/adm/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
EOF;

//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/jquery-form/jquery.form.min.js"></script>
    <script src="/adm/plugins/jquery-validation/jquery.validate.js"></script>

    <script src="/adm/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    
    <!-- DataTables  & Plugins -->
    <script src="/adm/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/adm/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="/adm/plugins/jszip/jszip.min.js"></script>
    <script src="/adm/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="/adm/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
EOF;

///
$App::$footer_section_scripts = <<<EOF
    <script src="/adm/js/sections-handler.js?v=$js_files_version"></script>
    <script src="/app/working_hours/index.js?v=$js_files_version"></script>
EOF;

//
$App::setSectionInfo("Horarios de Trabajo", "horarios");

?>

<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'header.phtml'; ?>
<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'aside-menu.phtml'; ?>
<?php 

include PATH_VIEWS_ADMIN.DS.'common'.DS.'secondary-nav-helper.php'; 


$custom_html = '
    <button type="button" class="btn btn-primary" id="btnAddWorkingHours">
        <i class="fas fa-plus me-2"></i>Add
    </button>
    <button type="button" class="btn btn-outline-secondary" id="btnReloadWorkingHours" title="Recargar">
        <i class="fas fa-sync"></i>
    </button>
';

?>

<?= renderSecondaryNavigation($App, $user_info, ['dropdown_title' => 'Catalogs'], $custom_html, null); ?>


<!-- Main Content -->
<main class="container-fluid mt-4" <?=$sidebar_margin;?>>
    

        <!-- Data Table -->
        <div class="card">
            <div class="card-body">
                <table id="grid_working_hours" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Folio#</th>
                            <th>Nombre Horario</th>
                            <th>Estatus</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

</main>

<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'footer.phtml'; ?>