<?php

//
include PATH_BASE.DS.'js_versioning.phtml';
//
$user_info = $App::GetUserData();
//var_dump($user_info); exit;





//
$App::$header_scrits = <<<EOF
    <!-- DataTables -->
    <link rel="stylesheet" href="/adm/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
EOF;


//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/jquery-form/jquery.form.min.js"></script>
    <script src="/adm/plugins/jquery-validation/jquery.validate.js"></script>
    <script src="/adm/plugins/jquery.fileDownload.js"></script>
    
    <script src="/adm/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    
    <!-- DataTables  & Plugins -->
    <script src="/adm/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/adm/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="/adm/plugins/jszip/jszip.min.js"></script>
    <script src="/adm/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="/adm/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
EOF;




///
$App::$footer_section_scripts = <<<EOF
    <script src="/adm/js/sections-handler.js?v=$js_files_version"></script>
    <script src="/app/notifications/index.js?v=$js_files_version"></script>
EOF;



//
$App::setSectionInfo("Notificaciones", "notifications", "notifications");


?>

<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'header.phtml'; ?>
<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'aside-menu.phtml'; ?>




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">

                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active"><?=$App::getSectionTitle();?></li>
                        </ol>


                    </div><!-- /.col -->
                    <div class="col-sm-6 text-right">

                        <button type="button" class="btn btn-flat btn-success btnAddRecord"><i class="fas fa-rocket"></i> Add Notification </button>
                        <button type="button" class="btn btn-flat btn-default btnReload"><i class="fas fa-sync"></i> </button>

                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12 text-right">

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">

                        <div class="row mb-3">

                            <div class="col-sm-2 col-md-2 col-lg-2 col-12">
                                <div class="form-group">
                                    <div class="text-primary">Week Date</div>
                                    <div class="input-group date" id="event_date" data-target-input="nearest">
                                        <input type="text" class="form-control form-control-sm datetimepicker-input" data-target="#event_date" readonly />
                                        <div class="input-group-append" data-target="#event_date" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-2 col-md-2 col-lg-2 col-12">
                                <div class="text-primary">Product Type</div>
                                <select class="form-control form-control-sm" id="filter_sale_type_id"></select>
                            </div>

                            <div class="col-sm-2 col-md-2 col-lg-2 col-12">
                                <div class="text-primary">Sales Status</div>
                                <select class="form-control form-control-sm" id="filter_status_id"></select>
                            </div>

                        </div>


<!--                        <div class="row mb-3">-->
<!--                            <div class="col-sm-2 col-md-2 col-lg-2 col-12">-->
<!--                                <form method="post" id="form_section" name="form_section" enctype="multipart/form-data">-->
<!--                                    <select class="form-control" style="" data-rule-number="true" id="store_id" name="store_id"></select>-->
<!--                                </form>-->
<!--                            </div>-->
<!--                        </div>-->


                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="grid_section" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>Id:</th>
                                        <th>Customer:</th>
                                        <th>Items:</th>
                                        <th>Total</th>
                                        <th>Payments</th>
                                        <th>Date</th>
                                        <th>Status:</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->


                    </div>
                </div>
                <!-- /.row -->



            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>



<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'footer.phtml'; ?>