<?php

//
include PATH_BASE.DS.'js_versioning.phtml';
//
$user_info = $App::GetUserData();
//var_dump($user_info); exit;



//
$App::$header_scrits = <<<EOF
    <!-- DataTables -->
    <link rel="stylesheet" href="/adm/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
EOF;


//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/jquery-form/jquery.form.min.js"></script>
    <script src="/adm/plugins/jquery-validation/jquery.validate.js"></script>
    
    <!-- DataTables  & Plugins -->
    <script src="/adm/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/adm/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="/adm/plugins/jszip/jszip.min.js"></script>
    <script src="/adm/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="/adm/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
EOF;




///
$App::$footer_section_scripts = <<<EOF
    <script src="/adm/js/sections-handler.js?v=$js_files_version"></script>
    <script src="/sup/accounts/index.js?v=$js_files_version"></script>
EOF;



//
$App::setSectionInfo("Accounts", "accounts");


?>

<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'header.phtml'; ?>
<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'aside-menu.phtml'; ?>




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">

                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active"><?=$App::getSectionTitle();?></li>
                        </ol>


                    </div><!-- /.col -->
                    <div class="col-sm-6 text-right">

                        <button type="button" class="btn btn-flat btn-primary btnAddRecord"><i class="fas fa-plus"></i> Add </button>
                        <button type="button" class="btn btn-flat btn-default btnReload"><i class="fas fa-sync"></i> </button>


                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12 text-right">

                    </div>
                </div>

                <div class="row">
                    <div class="col-12">


                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="grid_section" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>Folio:</th>
                                        <th>Empresa:</th>
                                        <th>Contacto:</th>
                                        <th>Notas:</th>
                                        <th>Activo:</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->


                    </div>
                </div>
                <!-- /.row -->



            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>



<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'footer.phtml'; ?>