<?php

//
include PATH_BASE.DS.'js_versioning.phtml';
//
$user_info = $App::GetUserData();
//var_dump($user_info); exit;




//
$App::$header_scrits = <<<EOF
    <!-- DataTables -->
    <link rel="stylesheet" href="/adm/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/select2/css/select2.min.css">
EOF;


//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/jquery-form/jquery.form.min.js"></script>
    <script src="/adm/plugins/jquery-validation/jquery.validate.js"></script>
    
    <script src="/adm/plugins/select2/js/select2.full.min.js"></script>
    <script src="/adm/plugins/select2/js/i18n/es.js"></script>
    <script src="/adm/js/s2-extended.js"></script>

    <!-- DataTables  & Plugins -->
    <script src="/adm/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/adm/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="/adm/plugins/jszip/jszip.min.js"></script>
    <script src="/adm/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="/adm/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
EOF;



//
$App::$footer_section_scripts = <<<EOF
    <script src="/adm/js/sections-handler.js?v=$js_files_version"></script>
    <script src="/app/invoices/index.js?v=$js_files_version"></script>
EOF;



//
$App::setSectionInfo("Invoices", "invoices ");


?>

<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'header.phtml'; ?>
<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'aside-menu.phtml'; ?>




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6 col-md-6 col-12">

                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active"><?=$App::getSectionTitle();?></li>
                        </ol>


                    </div><!-- /.col -->
                    <div class="col-sm-3 col-md-3 col-12">
                        <form method="post" id="form_upload" name="form_upload" enctype="multipart/form-data">
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="xls_file">
                                    <label class="custom-file-label" for="exampleInputFile">Import xls:</label>
                                </div>
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-flat btn-outline-primary"><i class="fas fa-upload"></i> Import </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-3 col-md-3 col-12 text-right">


                    

                        <button type="button" class="btn btn-flat btn-primary btnAddRecord"><i class="fas fa-plus"></i> Add </button>

                        <button type="button" class="btn btn-flat btn-default btnReload"><i class="fas fa-sync"></i> </button>


                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-sm-2 col-md-2 col-lg-2 col-12">

                        <div id="search_customer_container" style="border-radius:25px;padding:15px;">
                            <label for="search_customer_id">Buscar Cliente</label>
                            <select class="form-control inpt-search" data-rule-required="true" data-msg-required="..." data-rule-number="true" id="search_customer_id" name="search_customer_id"></select>
                        </div>

                    </div>
                </div>



                <div class="row mt-4">
                    <div class="col-12">


                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="grid_section" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th>Folio:</th>
                                        <th>Cliente:</th>
                                        <th>Items:</th>
                                        <th>Ventas:</th>
                                        <th>Comisiones:</th>
                                        <th>Por Cobrar:</th>
                                        <th>Status:</th>
                                        <th>Status Date:</th>                                   
                                        <th></th>
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->


                    </div>
                </div>
                <!-- /.row -->



            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>



<?php include PATH_VIEWS_ADMIN.DS.'common'.DS.'footer.phtml'; ?>