<?php

//
include PATH_BASE.DS.'js_versioning.phtml';
//
$user_info = $App::GetUserData();
//var_dump($user_info); exit;





//
$App::$header_scrits = <<<EOF
    <link rel="stylesheet" href="/adm/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="/adm/plugins/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="/adm/plugins/summernote/summernote-bs4.min.css">
EOF;


//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/chart.js/Chart.min.js"></script>
    <script src="/adm/plugins/sparklines/sparkline.js"></script>
    <script src="/adm/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="/adm/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <script src="/adm/plugins/jquery-knob/jquery.knob.min.js"></script>
    <script src="/adm/plugins/moment/moment.min.js"></script>
    <script src="/adm/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="/adm/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="/adm/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="/adm/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
EOF;




///
$App::$footer_section_scripts = <<<EOF
    <script src="/app/demo.js"></script>
    <script src="/app/dashboard.js?v=$js_files_version"></script>
EOF;




//
$App::setSectionInfo("Dashboard", "dashboard");

?>

<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'header.phtml'; ?>
<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'aside-menu.phtml'; ?>




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0"><?=$App::getSectionTitle();?></h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active"><?=$App::getSectionTitle();?></li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                
                <h4 class="my-5"> Bienenido admin </h4>
                
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>



<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'footer.phtml'; ?>