<?php

//
include PATH_BASE.DS.'js_versioning.phtml';


//
$App::$header_scrits = <<<EOF

EOF;





//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/jquery-form/jquery.form.min.js"></script>
    <script src="/adm/plugins/jquery-validation/jquery.validate.js"></script>
EOF;




///
$App::$footer_section_scripts = <<<EOF
    <script src="/sup/login.js?v=$js_files_version"></script>
EOF;



//
$App::setSectionInfo("Login", "login");
?>

<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'header-login.phtml'; ?>


<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="/admin/"><b><?=SUPADMIN_TITLE;?></b> Platform</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Login with your credentials</p>

            <form method="post" enctype="multipart/form-data" id="form_login_auth" name="form_login_auth" class="smart-form client-form">
                <div class="input-group mb-3">
                    <input type="email" class="form-control" data-rule-required="true" data-rule-email="true" id="username" name="username" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" data-rule-required="true" id="password" name="password" data-rule-minlength="3" data-rule-maxlength="26" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Remember
                            </label>
                        </div>
                    </div>
                </div>


                <div class="social-auth-links text-center mb-3">
                    <button type="submit" class="btn btn-block btn-primary">
                        <i class="fas fa-paper-plane mr-2"></i> Login
                    </button>
                </div>
                <!-- /.social-auth-links -->

            </form>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->



<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'footer-login.phtml'; ?>




