<?php

//
include PATH_BASE.DS.'js_versioning.phtml';
//
$user_info = $App::GetUserData();
//var_dump($user_info); exit;



//
$App::$header_scrits = <<<EOF
    <!-- DataTables -->
    <link rel="stylesheet" href="/adm/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/adm/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
EOF;


//
$App::$footer_scripts = <<<EOF
    <script src="/adm/plugins/jquery-form/jquery.form.min.js"></script>
    <script src="/adm/plugins/jquery-validation/jquery.validate.js"></script>
    
    <!-- DataTables  & Plugins -->
    <script src="/adm/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/adm/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/adm/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="/adm/plugins/jszip/jszip.min.js"></script>
    <script src="/adm/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="/adm/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="/adm/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
EOF;




///
$App::$footer_section_scripts = <<<EOF
    <script>
        var record_id = $record_id;
    </script>
    <script src="/adm/js/sections-handler.js?v=$js_files_version"></script>
    <script src="/sup/administrators/edit.js?v=$js_files_version"></script>
EOF;



//
$App::setSectionInfo("Usuarios", "administrators");


?>

<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'header.phtml'; ?>
<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'aside-menu.phtml'; ?>




    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">

                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active"><?=$App::getSectionTitle();?></li>
                        </ol>


                    </div><!-- /.col -->
                    <div class="col-sm-6 text-right">

                        <a href="/adm27/administrators/index" class="btn btn-flat btn-warning"><i class="fas fa-reply"></i> Back </a>

                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->



        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">

                        <!-- Profile Image -->
                        <div class="card card-primary card-outline">

                            <div class="card-body box-profile">
                                <div class="text-center">

                                    <div id="img_section_container" style="display:none">
                                        <img id="img_section_url" class="profile-user-img img-fluid img-circle">
                                    </div>
                                    <label class="btn btn-outline-primary btn-xs" style="margin-top:6px;">
                                        <form method="post" id="form_foto" name="form_foto" enctype="multipart/form-data">
                                            <i class="fas fa-upload"></i> Subir <input type="file" id="img_section" name="img_section" hidden>
                                        </form>
                                    </label>

                                </div>


                                <h3 class="empleado-nombre text-center"></h3>

                                <p class="empleado-titulo text-muted text-center"></p>


                                <div class="text-center mb-3 empleado-badges"></div>


                                <hr>

                                <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>
                                <p class="text-muted empleado-notes"></p>



                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->


                    </div>
                    <!-- /.col -->
                    <div class="col-md-9">


                        <div class="card card-primary card-outline card-tabs">
                            <div class="card-header p-0 pt-1 border-bottom-0">
                                <ul class="nav nav-tabs" id="custom-tabs-three-tab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="tab-detalles" data-toggle="pill" href="#detalles" role="tab" aria-controls="detalles" aria-selected="true">Info</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link permisos_info" id="tab-sucursales" data-toggle="pill" href="#sucursales" role="tab" aria-controls="sucursales" aria-selected="false">Sucursales</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="card-body">
                                <div class="tab-content" id="custom-tabs-three-tabContent">
                                    <div class="tab-pane fade show active" id="detalles" role="tabpanel" aria-labelledby="tab-detalles">
                                        <div class="overlay-wrapper">
                                            <div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">Loading...</div></div>

                                            <form method="post" id="form_section" name="form_section" enctype="multipart/form-data">

                                                <div class="row">
                                                    <div class="col-sm-6 col-lg-6 col-md-6 col-12">
                                                        <h4>Detalles - <span class="section-title"></span></h4>
                                                    </div>
                                                    <div class="col-sm-6 col-lg-6 col-md-6 col-12 text-right">
                                                        <button type="submit" class="btn btn-success">
                                                            <i class="fa fa-save"></i> Save
                                                        </button>
                                                        <button type="button" class="btn btn-flat btn-default" id="btnReloadDetails"><i class="fas fa-sync"></i> </button>
                                                    </div>
                                                </div>


                                                <hr />


                                                <div class="row">
                                                    <div class="col-sm-12 col-md-12 col-lg-12 col-12">
                                                        <div class="form-group">
                                                            <label for="nombre">Nombre:</label>
                                                            <input data-rule-required="true" type="text" class="form-control" name="nombre" id="nombre" placeholder="nombre...">
                                                        </div>
                                                    </div>
                                                </div>


                                                <div class="row">
                                                    <div class="col-sm-5 col-md-5 col-lg-5 col-12">
                                                        <div class="form-group">
                                                            <label for="email">Email:</label>
                                                            <input data-rule-required="true" data-rule-email="true" type="text" class="form-control" name="email" id="email">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-3 col-md-3 col-lg-3 col-12">
                                                        <label for="phone_cc">Telefono Clave:</label>
                                                        <Select class="form-control" name="phone_cc" id="phone_cc">
                                                            <option>--select</option>
                                                            <option value="+1" selected>US(+1)</option>
                                                            <option value="+52">MEX(+52)</option>
                                                        </Select>
                                                    </div>
                                                    <div class="col-sm-4 col-md-4 col-lg-4 col-12">
                                                        <label for="phone_number">Telefono:</label>
                                                        <input type="text" class="form-control" name="phone_number" id="phone_number" placeholder="Telefono...">
                                                    </div>
                                                </div>


                                                <br />


                                                <div class="row">
                                                    <div class="col-sm-6 col-12">
                                                        <div class="form-group">
                                                            <label for="password">Clave:</label>
                                                            <input type="password" class="form-control" name="password" id="password">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6 col-12">
                                                        <div class="form-group">
                                                            <label for="password_confirm">Confirmar Clave:</label>
                                                            <input type="password" class="form-control" name="password_confirm" id="password_confirm">
                                                        </div>
                                                    </div>
                                                </div>


                                                <br />


                                                <div class="row">
                                                    <div class="col-md-6 col-lg-6 col-12 text-center">
                                                        <br />
                                                        <br />
                                                        <label class="checkbox-inline">
                                                            <input type="checkbox" class="styled-checkbox" id="active" name="active"> <strong> Habilitado </strong>
                                                        </label>
                                                    </div>
                                                    <div class="col-md-6 col-lg-6 col-12">
                                                        <div class="form-group">
                                                            <label for="notes">Notas:</label>
                                                            <textarea data-rule-maxlength="512" type="text" class="form-control" name="notes" id="notes" placeholder=""></textarea>
                                                        </div>
                                                    </div>
                                                </div>



                                            </form>


                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="sucursales" role="tabpanel" aria-labelledby="tab-sucursales">
                                        <div class="overlay-wrapper">
                                            <div class="overlay"><i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">Loading...</div></div>

                                            <form method="post" id="form_sucursales" name="form_sucursales" enctype="multipart/form-data">


                                                <div class="row">
                                                    <div class="col-sm-6 col-lg-6 col-md-6 col-12">
                                                        <h4>Sucursales - <span class="empleado-nombre"></span></h4>
                                                    </div>
                                                    <div class="col-sm-3 col-lg-3 col-md-3 col-12">
                                                        <label for="sucursal_id">Seleccionar Sucursal:</label>
                                                        <select class="form-control" data-rule-required="true" id="sucursal_id" name="sucursal_id"></select>
                                                    </div>
                                                    <div class="col-sm-3 col-lg-3 col-md-3 col-12">
                                                        <br />
                                                        <button type="submit" class="btn btn-success"><span class="fa fa-plus"></span> Add </button>
                                                        <button type="button" class="btn btn-flat btn-default" id="btnReloadSucursales"><i class="fas fa-sync"></i> </button>
                                                    </div>
                                                </div>

                                                <br />

                                                <div class="row">
                                                    <div class="col-12">
                                                        <div class="card">
                                                            <!-- /.card-header -->
                                                            <div class="card-body">
                                                                <table id="grid_empleado_sucursales" class="table table-bordered table-striped">
                                                                    <thead>
                                                                    <tr>
                                                                        <th></th>
                                                                        <th>Folio:</th>
                                                                        <th>empleado_id:</th>
                                                                        <th>Sucursal:</th>
                                                                        <th>Estado:</th>
                                                                        <th>Permisos:</th>
                                                                        <th></th>
                                                                    </tr>
                                                                    </thead>
                                                                </table>
                                                            </div>
                                                            <!-- /.card-body -->
                                                        </div>
                                                        <!-- /.card -->
                                                    </div>
                                                </div>
                                                <!-- /.row -->

                                            </form>

                                        </div>
                                    </div>
                                </div>
                                <div class="tab-custom-content">
                                    <div class="row controls-row">
                                        <div class="col-lg-12 col-md-12 text-right">
                                            <small>folio: <strong id="registro_folio"></strong>, fecha creacion: <strong id="registro_fecha_creacion"></strong></small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card -->


                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>




    </div><!-- /.container-fluid -->



<?php include PATH_VIEWS_SUPADMIN.DS.'common'.DS.'footer.phtml'; ?>